version: "3.5"
services:
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube:10.6.0-community"
    ports:
      - "9000:9000"
      - "9092:9092"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - "./demo-server/conf:/opt/sonarqube/conf"
      - "./demo-server/data:/opt/sonarqube/data"
      - "./demo-server/logs:/opt/sonarqube/logs"
      - "./demo-server/extensions:/opt/sonarqube/extensions"
    restart: no
  db:
    container_name: "sonarqube-db"
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - "./demo-server/postgresql:/var/lib/postgresql"
      - "./demo-server/postgresql_data:/var/lib/postgresql/data"
    restart: no
